INSERT INTO settings(key, value) VALUES
    ('dbversion', '1'),
    ('equityRefreshRate', '120'),
    ('equityTradeCost', '0.00'),
    ('equityTradeCostNonExchange', '6.95'),
    ('equityWatchLists', 'WATCH'),
    ('history', '0'),
    ('marketTypes', 'BOND,EQUITY,FOREX,FUTURE,OPTION'),
    ('numDays', '365.25'),
    ('numTradingDays', '252.75'),
    ('optionChainRefreshRate', '120'),
    ('optionChainExpiryEndDate', '28'),
    ('optionChainWatchLists', 'WATCH'),
    ('optionTradeCost', '0.65'),
    ('palette', 'DARK'),
    ('paletteHighlight', '#2a82da');

INSERT INTO marketType(type, hasMarketHours) VALUES
    ('BOND', true),
    ('EQUITY', true),
    ('ETF', false),
    ('FOREX', true),
    ('FUTURE', true),
    ('FUTURE_OPTION', false),
    ('INDEX', false),
    ('INDICATOR', false),
    ('MUTUAL_FUND', false),
    ('OPTION', true),
    ('UNKNOWN', false);

INSERT INTO productType(type) VALUES
    ('NULL');

INSERT INTO sessionHoursType(type, isExtendedHours, isElectronic) VALUES
    ('POST_MARKET', true, true),
    ('PRE_MARKET', true, true),
    ('REGULAR_MARKET', false, true),
    ('OUTCRY_MARKET', false, false);

INSERT INTO indices(name, description) VALUES
    ('DJX.X', 'Dow Jones Indu Index'),
    ('COMPX', 'NASDAQ Composite'),
    ('NDX.X', 'NASDAQ 100'),
    ('OEX.X', 'S&P 100'),
    ('SPX.X', 'S&P 500 Index');

/* used https://wikitable2csv.ggor.de/ to translate wikipedia lists to generate this table */
INSERT INTO watchlist(name, symbol, description) VALUES
    ('OEX.X', 'AAPL', 'Apple Inc.'),
    ('OEX.X', 'ABBV', 'AbbVie Inc.'),
    ('OEX.X', 'ABT', 'Abbott Laboratories'),
    ('OEX.X', 'ACN', 'Accenture'),
    ('OEX.X', 'ADBE', 'Adobe Inc.'),
    ('OEX.X', 'AIG', 'American International Group'),
    ('OEX.X', 'ALL', 'Allstate'),
    ('OEX.X', 'AMGN', 'Amgen Inc.'),
    ('OEX.X', 'AMT', 'American Tower'),
    ('OEX.X', 'AMZN', 'Amazon.com'),
    ('OEX.X', 'AXP', 'American Express'),
    ('OEX.X', 'BA', 'Boeing Co.'),
    ('OEX.X', 'BAC', 'Bank of America Corp'),
    ('OEX.X', 'BIIB', 'Biogen'),
    ('OEX.X', 'BK', 'The Bank of New York Mellon'),
    ('OEX.X', 'BKNG', 'Booking Holdings'),
    ('OEX.X', 'BLK', 'BlackRock Inc'),
    ('OEX.X', 'BMY', 'Bristol-Myers Squibb'),
    ('OEX.X', 'BRK.B', 'Berkshire Hathaway'),
    ('OEX.X', 'C', 'Citigroup Inc'),
    ('OEX.X', 'CAT', 'Caterpillar Inc.'),
    ('OEX.X', 'CHTR', 'Charter Communications'),
    ('OEX.X', 'CL', 'Colgate-Palmolive'),
    ('OEX.X', 'CMCSA', 'Comcast Corp.'),
    ('OEX.X', 'COF', 'Capital One Financial Corp.'),
    ('OEX.X', 'COP', 'ConocoPhillips'),
    ('OEX.X', 'COST', 'Costco Wholesale Corp.'),
    ('OEX.X', 'CRM', 'Salesforce'),
    ('OEX.X', 'CSCO', 'Cisco Systems'),
    ('OEX.X', 'CVS', 'CVS Health'),
    ('OEX.X', 'CVX', 'Chevron Corporation'),
    ('OEX.X', 'DD', 'DuPont de Nemours Inc'),
    ('OEX.X', 'DHR', 'Danaher Corporation'),
    ('OEX.X', 'DIS', 'The Walt Disney Company'),
    ('OEX.X', 'DOW', 'Dow Inc.'),
    ('OEX.X', 'DUK', 'Duke Energy'),
    ('OEX.X', 'EMR', 'Emerson Electric Co.'),
    ('OEX.X', 'EXC', 'Exelon'),
    ('OEX.X', 'F', 'Ford Motor Company'),
    ('OEX.X', 'FB', 'Facebook, Inc.'),
    ('OEX.X', 'FDX', 'FedEx'),
    ('OEX.X', 'GD', 'General Dynamics'),
    ('OEX.X', 'GE', 'General Electric'),
    ('OEX.X', 'GILD', 'Gilead Sciences'),
    ('OEX.X', 'GM', 'General Motors'),
    ('OEX.X', 'GOOG', 'Alphabet Inc. (Class C)'),
    ('OEX.X', 'GOOGL', 'Alphabet Inc. (Class A)'),
    ('OEX.X', 'GS', 'Goldman Sachs'),
    ('OEX.X', 'HD', 'The Home Depot'),
    ('OEX.X', 'HON', 'Honeywell'),
    ('OEX.X', 'IBM', 'International Business Machines'),
    ('OEX.X', 'INTC', 'Intel Corp.'),
    ('OEX.X', 'JNJ', 'Johnson & Johnson'),
    ('OEX.X', 'JPM', 'JPMorgan Chase & Co.'),
    ('OEX.X', 'KHC', 'Kraft Heinz'),
    ('OEX.X', 'KMI', 'Kinder Morgan'),
    ('OEX.X', 'KO', 'The Coca-Cola Company'),
    ('OEX.X', 'LLY', 'Eli Lilly and Company'),
    ('OEX.X', 'LMT', 'Lockheed Martin'),
    ('OEX.X', 'LOW', 'Lowe''s'),
    ('OEX.X', 'MA', 'Mastercard'),
    ('OEX.X', 'MCD', 'McDonald''s Corp'),
    ('OEX.X', 'MDLZ', 'Mondelēz International'),
    ('OEX.X', 'MDT', 'Medtronic plc'),
    ('OEX.X', 'MET', 'MetLife Inc.'),
    ('OEX.X', 'MMM', '3M Company'),
    ('OEX.X', 'MO', 'Altria Group'),
    ('OEX.X', 'MRK', 'Merck & Co.'),
    ('OEX.X', 'MS', 'Morgan Stanley'),
    ('OEX.X', 'MSFT', 'Microsoft'),
    ('OEX.X', 'NEE', 'NextEra Energy'),
    ('OEX.X', 'NFLX', 'Netflix'),
    ('OEX.X', 'NKE', 'Nike, Inc.'),
    ('OEX.X', 'NVDA', 'Nvidia Corporation'),
    ('OEX.X', 'ORCL', 'Oracle Corporation'),
    ('OEX.X', 'PEP', 'PepsiCo'),
    ('OEX.X', 'PFE', 'Pfizer Inc'),
    ('OEX.X', 'PG', 'Procter & Gamble'),
    ('OEX.X', 'PM', 'Philip Morris International'),
    ('OEX.X', 'PYPL', 'PayPal'),
    ('OEX.X', 'QCOM', 'Qualcomm'),
    ('OEX.X', 'RTX', 'Raytheon Technologies'),
    ('OEX.X', 'SBUX', 'Starbucks Corp.'),
    ('OEX.X', 'SLB', 'Schlumberger'),
    ('OEX.X', 'SO', 'Southern Company'),
    ('OEX.X', 'SPG', 'Simon Property Group'),
    ('OEX.X', 'T', 'AT&T Inc'),
    ('OEX.X', 'TGT', 'Target Corporation'),
    ('OEX.X', 'TMO', 'Thermo Fisher Scientific'),
    ('OEX.X', 'TSLA', 'Tesla, Inc.'),
    ('OEX.X', 'TXN', 'Texas Instruments'),
    ('OEX.X', 'UNH', 'UnitedHealth Group'),
    ('OEX.X', 'UNP', 'Union Pacific Corporation'),
    ('OEX.X', 'UPS', 'United Parcel Service'),
    ('OEX.X', 'USB', 'U.S. Bancorp'),
    ('OEX.X', 'V', 'Visa Inc.'),
    ('OEX.X', 'VZ', 'Verizon Communications'),
    ('OEX.X', 'WBA', 'Walgreens Boots Alliance'),
    ('OEX.X', 'WFC', 'Wells Fargo'),
    ('OEX.X', 'WMT', 'Walmart'),
    ('OEX.X', 'XOM', 'Exxon Mobil Corp.'),
    ('WATCH', 'AJAX', 'Ajax I'),
    ('WATCH', 'PRTY', 'Party City Holdco Inc.'),
    ('WATCH', 'PSAC', 'Property Solutions Acquisition Corp.'),
    ('WATCH', 'SFT', 'Shift Technologies, Inc.'),
    ('WATCH', 'SWN', 'Southwestern Energy Company'),
    ('WATCH', 'ABEV', 'Ambev S.A.'),
    ('WATCH', 'X', 'United States Steel Corporation'),
    ('WATCH', 'AAL', 'American Airlines Group Inc.'),
    ('WATCH', 'ZNGA', 'Zynga Inc.'),
    ('WATCH', 'NCLH', 'Norwegian Cruise Line Holdings Ltd.'),
    ('WATCH', 'CCL', 'Carnival Corporation & plc'),
    ('WATCH', 'F', 'Ford Motor Company'),
    ('WATCH', 'T', 'AT&T Inc');

INSERT INTO accountTypes(type) VALUES
    ('CASH'),
    ('MARGIN');

INSERT INTO balanceTypes(type) VALUES
    ('CURRENT'),
    ('INITIAL'),
    ('PROJECTED');

INSERT INTO interestRateSources(name) VALUES
    ('TREAS_BILL'),
    ('TREAS_YIELD_CURVE');
