
DELETE FROM watchlist WHERE name='OEX.X';

INSERT INTO watchlist(name, symbol, description) VALUES
    ('DOW 30', 'AXP', 'American Express Co'),
    ('DOW 30', 'AMGN', 'Amgen Inc'),
    ('DOW 30', 'AAPL', 'Apple Inc'),
    ('DOW 30', 'BA', 'Boeing Co'),
    ('DOW 30', 'CAT', 'Caterpillar Inc'),
    ('DOW 30', 'CSCO', 'Cisco Systems Inc'),
    ('DOW 30', 'CVX', 'Chevron Corp'),
    ('DOW 30', 'GS', 'Goldman Sachs Group Inc'),
    ('DOW 30', 'HD', 'Home Depot Inc'),
    ('DOW 30', 'HON', 'Honeywell International Inc'),
    ('DOW 30', 'IBM', 'International Business Machines Corp'),
    ('DOW 30', 'INTC', 'Intel Corp'),
    ('DOW 30', 'JNJ', 'Johnson & Johnson'),
    ('DOW 30', 'KO', 'Coca-Cola Co'),
    ('DOW 30', 'JPM', 'JPMorgan Chase & Co'),
    ('DOW 30', 'MCD', 'McDonald''s Corp'),
    ('DOW 30', 'MMM', '3M Co'),
    ('DOW 30', 'MRK', 'Merck & Co Inc'),
    ('DOW 30', 'MSFT', 'Microsoft Corp'),
    ('DOW 30', 'NKE', 'Nike Inc'),
    ('DOW 30', 'PG', 'Procter & Gamble Co'),
    ('DOW 30', 'TRV', 'Travelers Companies Inc'),
    ('DOW 30', 'UNH', 'UnitedHealth Group Inc'),
    ('DOW 30', 'CRM', 'Salesforce.Com Inc'),
    ('DOW 30', 'VZ', 'Verizon Communications Inc'),
    ('DOW 30', 'V', 'Visa Inc'),
    ('DOW 30', 'WBA', 'Walgreens Boots Alliance Inc'),
    ('DOW 30', 'WMT', 'Walmart Inc'),
    ('DOW 30', 'DIS', 'Walt Disney Co'),
    ('DOW 30', 'DOW', 'Dow Inc'),
    ('NASDAQ 100', 'AMD', 'Advanced Micro Devices Inc'),
    ('NASDAQ 100', 'ADBE', 'Adobe Inc.'),
    ('NASDAQ 100', 'ALGN', 'Align Technology Inc'),
    ('NASDAQ 100', 'AMZN', 'Amazon.com Inc'),
    ('NASDAQ 100', 'AMGN', 'Amgen Inc'),
    ('NASDAQ 100', 'AEP', 'American Electric Power Company Inc'),
    ('NASDAQ 100', 'ADI', 'Analog Devices Inc'),
    ('NASDAQ 100', 'ANSS', 'ANSYS Inc'),
    ('NASDAQ 100', 'AAPL', 'Apple Inc'),
    ('NASDAQ 100', 'AMAT', 'Applied Materials Inc'),
    ('NASDAQ 100', 'ASML', 'ASML Holding NV'),
    ('NASDAQ 100', 'TEAM', 'Atlassian Corporation PLC'),
    ('NASDAQ 100', 'ADSK', 'Autodesk Inc'),
    ('NASDAQ 100', 'ATVI', 'Activision Blizzard Inc'),
    ('NASDAQ 100', 'ADP', 'Automatic Data Processing Inc'),
    ('NASDAQ 100', 'AVGO', 'Broadcom Inc'),
    ('NASDAQ 100', 'BIDU', 'Baidu Inc'),
    ('NASDAQ 100', 'BIIB', 'Biogen Inc'),
    ('NASDAQ 100', 'BMRN', 'Biomarin Pharmaceutical Inc'),
    ('NASDAQ 100', 'BKNG', 'Booking Holdings Inc'),
    ('NASDAQ 100', 'CDNS', 'Cadence Design Systems Inc'),
    ('NASDAQ 100', 'CDW', 'CDW Corp'),
    ('NASDAQ 100', 'CERN', 'Cerner Corp'),
    ('NASDAQ 100', 'CHKP', 'Check Point Software Technologies Ltd'),
    ('NASDAQ 100', 'CHTR', 'Charter Communications Inc'),
    ('NASDAQ 100', 'CPRT', 'Copart Inc'),
    ('NASDAQ 100', 'CRWD', 'CrowdStrike Holdings Inc'),
    ('NASDAQ 100', 'CTAS', 'Cintas Corp'),
    ('NASDAQ 100', 'CSCO', 'Cisco Systems Inc'),
    ('NASDAQ 100', 'CMCSA', 'Comcast Corp'),
    ('NASDAQ 100', 'COST', 'Costco Wholesale Corp'),
    ('NASDAQ 100', 'CSX', 'CSX Corp'),
    ('NASDAQ 100', 'CTSH', 'Cognizant Technology Solutions Corp'),
    ('NASDAQ 100', 'DOCU', 'DocuSign Inc'),
    ('NASDAQ 100', 'DXCM', 'Dexcom Inc'),
    ('NASDAQ 100', 'DLTR', 'Dollar Tree Inc'),
    ('NASDAQ 100', 'EA', 'Electronic Arts'),
    ('NASDAQ 100', 'EBAY', 'eBay Inc'),
    ('NASDAQ 100', 'EXC', 'Exelon Corp'),
    ('NASDAQ 100', 'FAST', 'Fastenal Co'),
    ('NASDAQ 100', 'FB', 'Facebook'),
    ('NASDAQ 100', 'FISV', 'Fiserv Inc'),
    ('NASDAQ 100', 'FOX', 'Fox Corp. Class B'),
    ('NASDAQ 100', 'FOXA', 'Fox Corp. Class A'),
    ('NASDAQ 100', 'GILD', 'Gilead Sciences Inc'),
    ('NASDAQ 100', 'GOOG', 'Alphabet Class C'),
    ('NASDAQ 100', 'GOOGL', 'Alphabet Class A'),
    ('NASDAQ 100', 'HON', 'Honeywell International Inc'),
    ('NASDAQ 100', 'ILMN', 'Illumina Inc'),
    ('NASDAQ 100', 'INCY', 'Incyte Corp'),
    ('NASDAQ 100', 'INTC', 'Intel Corp'),
    ('NASDAQ 100', 'INTU', 'Intuit Inc'),
    ('NASDAQ 100', 'ISRG', 'Intuitive Surgical Inc'),
    ('NASDAQ 100', 'MRVL', 'Marvell Technology Inc'),
    ('NASDAQ 100', 'IDXX', 'IDEXX Laboratories Inc'),
    ('NASDAQ 100', 'JD', 'JD.Com Inc'),
    ('NASDAQ 100', 'KDP', 'Keurig Dr Pepper Inc'),
    ('NASDAQ 100', 'KLAC', 'KLA Corp'),
    ('NASDAQ 100', 'KHC', 'Kraft Heinz Co'),
    ('NASDAQ 100', 'LRCX', 'Lam Research Corp'),
    ('NASDAQ 100', 'LULU', 'Lululemon Athletica Inc'),
    ('NASDAQ 100', 'MELI', 'Mercadolibre Inc'),
    ('NASDAQ 100', 'MAR', 'Marriott International Inc'),
    ('NASDAQ 100', 'MTCH', 'Match Group Inc'),
    ('NASDAQ 100', 'MCHP', 'Microchip Technology Inc'),
    ('NASDAQ 100', 'MDLZ', 'Mondelez International Inc'),
    ('NASDAQ 100', 'MRNA', 'Moderna Inc'),
    ('NASDAQ 100', 'MNST', 'Monster Beverage Corp'),
    ('NASDAQ 100', 'MSFT', 'Microsoft Corp'),
    ('NASDAQ 100', 'MU', 'Micron Technology Inc'),
    ('NASDAQ 100', 'NFLX', 'Netflix Inc'),
    ('NASDAQ 100', 'NTES', 'NetEase Inc'),
    ('NASDAQ 100', 'NVDA', 'NVIDIA Corp'),
    ('NASDAQ 100', 'NXPI', 'NXP Semiconductors NV'),
    ('NASDAQ 100', 'OKTA', 'Okta Inc'),
    ('NASDAQ 100', 'ORLY', 'O''Reilly Automotive Inc'),
    ('NASDAQ 100', 'PAYX', 'Paychex Inc'),
    ('NASDAQ 100', 'PCAR', 'Paccar Inc'),
    ('NASDAQ 100', 'PDD', 'Pinduoduo Inc'),
    ('NASDAQ 100', 'PTON', 'Peloton Interactive Inc'),
    ('NASDAQ 100', 'PYPL', 'PayPal Holdings Inc'),
    ('NASDAQ 100', 'PEP', 'PepsiCo Inc.'),
    ('NASDAQ 100', 'QCOM', 'Qualcomm Inc'),
    ('NASDAQ 100', 'REGN', 'Regeneron Pharmaceuticals Inc'),
    ('NASDAQ 100', 'ROST', 'Ross Stores Inc'),
    ('NASDAQ 100', 'SIRI', 'Sirius XM Holdings Inc'),
    ('NASDAQ 100', 'SGEN', 'Seagen Inc'),
    ('NASDAQ 100', 'SPLK', 'Splunk Inc'),
    ('NASDAQ 100', 'SWKS', 'Skyworks Solutions Inc'),
    ('NASDAQ 100', 'SBUX', 'Starbucks Corp'),
    ('NASDAQ 100', 'SNPS', 'Synopsys Inc'),
    ('NASDAQ 100', 'TCOM', 'Trip.com Group Ltd'),
    ('NASDAQ 100', 'TSLA', 'Tesla Inc'),
    ('NASDAQ 100', 'TXN', 'Texas Instruments Inc'),
    ('NASDAQ 100', 'TMUS', 'T-Mobile US Inc'),
    ('NASDAQ 100', 'VRSN', 'Verisign Inc'),
    ('NASDAQ 100', 'VRSK', 'Verisk Analytics Inc'),
    ('NASDAQ 100', 'VRTX', 'Vertex Pharmaceuticals Inc'),
    ('NASDAQ 100', 'WBA', 'Walgreens Boots Alliance Inc'),
    ('NASDAQ 100', 'WDAY', 'Workday Inc'),
    ('NASDAQ 100', 'XEL', 'Xcel Energy Inc'),
    ('NASDAQ 100', 'XLNX', 'Xilinx Inc'),
    ('NASDAQ 100', 'ZM', 'Zoom Video Communications Inc'),
    ('S&P 100', 'AAPL', 'Apple'),
    ('S&P 100', 'ABBV', 'AbbVie'),
    ('S&P 100', 'ABT', 'Abbott Laboratories'),
    ('S&P 100', 'ACN', 'Accenture'),
    ('S&P 100', 'ADBE', 'Adobe'),
    ('S&P 100', 'AIG', 'American International Group'),
    ('S&P 100', 'AMGN', 'Amgen'),
    ('S&P 100', 'AMT', 'American Tower'),
    ('S&P 100', 'AMZN', 'Amazon.com'),
    ('S&P 100', 'AVGO', 'Broadcom'),
    ('S&P 100', 'AXP', 'American Express'),
    ('S&P 100', 'BA', 'Boeing'),
    ('S&P 100', 'BAC', 'Bank of America'),
    ('S&P 100', 'BIIB', 'Biogen'),
    ('S&P 100', 'BK', 'BNY Mellon'),
    ('S&P 100', 'BKNG', 'Booking Holdings'),
    ('S&P 100', 'BLK', 'BlackRock'),
    ('S&P 100', 'BMY', 'Bristol Myers Squibb'),
    ('S&P 100', 'BRK.B', 'Berkshire Hathaway'),
    ('S&P 100', 'C', 'Citigroup'),
    ('S&P 100', 'CAT', 'Caterpillar'),
    ('S&P 100', 'CHTR', 'Charter Communications'),
    ('S&P 100', 'CL', 'Colgate-Palmolive'),
    ('S&P 100', 'CMCSA', 'Comcast'),
    ('S&P 100', 'COF', 'Capital One'),
    ('S&P 100', 'COP', 'ConocoPhillips'),
    ('S&P 100', 'COST', 'Costco'),
    ('S&P 100', 'CRM', 'Salesforce'),
    ('S&P 100', 'CSCO', 'Cisco Systems'),
    ('S&P 100', 'CVS', 'CVS Health'),
    ('S&P 100', 'CVX', 'Chevron'),
    ('S&P 100', 'DD', 'DuPont'),
    ('S&P 100', 'DHR', 'Danaher'),
    ('S&P 100', 'DIS', 'Disney'),
    ('S&P 100', 'DOW', 'Dow'),
    ('S&P 100', 'DUK', 'Duke Energy'),
    ('S&P 100', 'EMR', 'Emerson Electric'),
    ('S&P 100', 'EXC', 'Exelon'),
    ('S&P 100', 'F', 'Ford'),
    ('S&P 100', 'FB', 'Facebook'),
    ('S&P 100', 'FDX', 'FedEx'),
    ('S&P 100', 'GD', 'General Dynamics'),
    ('S&P 100', 'GE', 'General Electric'),
    ('S&P 100', 'GILD', 'Gilead Sciences'),
    ('S&P 100', 'GM', 'General Motors'),
    ('S&P 100', 'GOOG', 'Alphabet (Class C)'),
    ('S&P 100', 'GOOGL', 'Alphabet (Class A)'),
    ('S&P 100', 'GS', 'Goldman Sachs'),
    ('S&P 100', 'HD', 'Home Depot'),
    ('S&P 100', 'HON', 'Honeywell'),
    ('S&P 100', 'IBM', 'IBM'),
    ('S&P 100', 'INTC', 'Intel'),
    ('S&P 100', 'JNJ', 'Johnson & Johnson'),
    ('S&P 100', 'JPM', 'JPMorgan Chase'),
    ('S&P 100', 'KHC', 'Kraft Heinz'),
    ('S&P 100', 'KO', 'Coca-Cola'),
    ('S&P 100', 'LIN', 'Linde'),
    ('S&P 100', 'LLY', 'Eli Lilly'),
    ('S&P 100', 'LMT', 'Lockheed Martin'),
    ('S&P 100', 'LOW', 'Lowe''s'),
    ('S&P 100', 'MA', 'Mastercard'),
    ('S&P 100', 'MCD', 'McDonald''s'),
    ('S&P 100', 'MDLZ', 'Mondelēz International'),
    ('S&P 100', 'MDT', 'Medtronic'),
    ('S&P 100', 'MET', 'MetLife'),
    ('S&P 100', 'MMM', '3M'),
    ('S&P 100', 'MO', 'Altria'),
    ('S&P 100', 'MRK', 'Merck'),
    ('S&P 100', 'MS', 'Morgan Stanley'),
    ('S&P 100', 'MSFT', 'Microsoft'),
    ('S&P 100', 'NEE', 'NextEra Energy'),
    ('S&P 100', 'NFLX', 'Netflix'),
    ('S&P 100', 'NKE', 'Nike'),
    ('S&P 100', 'NVDA', 'Nvidia'),
    ('S&P 100', 'ORCL', 'Oracle'),
    ('S&P 100', 'PEP', 'PepsiCo'),
    ('S&P 100', 'PFE', 'Pfizer'),
    ('S&P 100', 'PG', 'Procter & Gamble'),
    ('S&P 100', 'PM', 'Philip Morris International'),
    ('S&P 100', 'PYPL', 'PayPal'),
    ('S&P 100', 'QCOM', 'Qualcomm'),
    ('S&P 100', 'RTX', 'Raytheon Technologies'),
    ('S&P 100', 'SBUX', 'Starbucks'),
    ('S&P 100', 'SO', 'Southern Company'),
    ('S&P 100', 'SPG', 'Simon Property Group'),
    ('S&P 100', 'T', 'AT&T'),
    ('S&P 100', 'TGT', 'Target'),
    ('S&P 100', 'TMO', 'Thermo Fisher Scientific'),
    ('S&P 100', 'TMUS', 'T-Mobile US'),
    ('S&P 100', 'TSLA', 'Tesla'),
    ('S&P 100', 'TXN', 'Texas Instruments'),
    ('S&P 100', 'UNH', 'UnitedHealth'),
    ('S&P 100', 'UNP', 'Union Pacific'),
    ('S&P 100', 'UPS', 'United Parcel Service'),
    ('S&P 100', 'USB', 'U.S. Bancorp'),
    ('S&P 100', 'V', 'Visa'),
    ('S&P 100', 'VZ', 'Verizon'),
    ('S&P 100', 'WBA', 'Walgreens Boots Alliance'),
    ('S&P 100', 'WFC', 'Wells Fargo'),
    ('S&P 100', 'WMT', 'Walmart'),
    ('S&P 100', 'XOM', 'ExxonMobil');
